### ISSUE TITLE
Guest basket is not available for authenticated user even after call "updateCustomerForBasket"

### ISSUE THREAD

**Issue by acibilous** [SalesforceCommerceCloud/commerce-sdk#290]
**Steps:**
1. Create a guest session
2. Create a basket using the guest token
3. Authorize the user
4. Call "updateCustomerForBasket" with info of the authorized user
4. Try to get the basket with a token of authorized user

**Expected result:**
The basket should be available for an authorized user

**Actual result:**
The basket is available only with a token of guest user

**Comment by niknarayanan** [comment]
Hi,
The basket created with the guest user token is not be accessible with the registered user token because the customer ids differ in this case. One way to achieve the cart merge is to use the new SLAS service (which should be available with the SDK in about a month) which allows you to pass the unique USID between guest and registered shopper JWTs. 

When not using SLAS, you can achieve this using the following two steps: 
1. Use a GET/baskets call to get the basket with the guest token
2. Submit the basket retrieved in step#1 using POST/baskets with the registered user token. 

Note: We are currently looking into providing better API support for basket merge use-case and will keep you posted. Hope this helps for now.

**Comment by monkey-jeff** [comment]
Just linking the conversation from CCDC around this issue.

https://developer.commercecloud.com/s/question/0D53k00006u1l1ECAQ/how-to-reassign-basket-from-guest-user-to-the-registered-one
