### ISSUE TITLE
can't get order with Checkout.Orders client

### ISSUE THREAD

**Issue by ajendrex** [SalesforceCommerceCloud/commerce-sdk#333]
Hello,

We need to get an order using Orders API, because some fields only come when using that instead of Shopper Orders, but we can't see how to do it with the sdk. There is no "getOrder" method in the documentation https://salesforcecommercecloud.github.io/commerce-sdk/classes/checkout.orders.html.

Is there another way to do this?

**Comment by gkhunger-sf** [comment]
Hi Héctor,

Since addition of getOrders to the orders API we haven't been able to release a new version of the SDK. We'll release the new version of the SDK with these changes in our next release window which is about a week from now. We'll let you know once the new version has been released.

Cheers,
Gaurav

**Comment by ajendrex** [comment]
Hello @gkhunger-sf

We will wait for it. Thank you!

H.

**Comment by wjhsf** [comment]
Hi @ajendrex, we have released [v2.5.0](https://github.com/SalesforceCommerceCloud/commerce-sdk/releases/tag/v2.5.0), which adds the `getOrder` and `getOrders` methods to the Orders API.
