### ISSUE TITLE
unable to download nanoid dependency on installing commerce-sdk

### ISSUE THREAD

**Issue by Sebashish** [SalesforceCommerceCloud/commerce-sdk#368]
Following this step by using node 16 LTS: https://developer.salesforce.com/docs/commerce/commerce-api/guide/api-and-sdk-demo.html

And then got this issue
<img width="724" alt="Screenshot 2022-07-11 at 4 31 49 PM" src="https://user-images.githubusercontent.com/38973944/178250557-998a8d37-6598-405e-b4aa-55ae566c2c6f.png">

Using this node version:
<img width="311" alt="Screenshot 2022-07-11 at 4 31 29 PM" src="https://user-images.githubusercontent.com/38973944/178250612-138c907d-1fc7-45ba-8493-4bb7aa8140b8.png">

This could be because this is listed as a devDependency.

**Comment by Sebashish** [comment]
@johnboxall @SalesforceCommerceCloud/commerce-cloud-services can you guys please have a look into this. Thanks!

**Comment by johnboxall** [comment]
Hey folks,

I believe this issue is coming up because we've included `nanoid` as a `devDependancy` as opposed to a `dependancy`:

https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/6874c86162ce63bc74efa18c94a96f2885347b19/package.json#L74

It isn't possible to work around this using `npm install nanoid` as you end up with a `ERR_REQUIRE_ESM` error.

**As a workaround, you can use `commerce-sdk@2.7.1` before helpers that use `nanoid` were introduced.**

**Comment by joeluong-sfcc** [comment]
Thank you for creating this issue @Sebashish. I am now closing this issue as [v2.10.1](https://github.com/SalesforceCommerceCloud/commerce-sdk/releases/tag/v2.10.1) of the `commerce-sdk` resolves this issue
